"""Descripción del cambio

Revision ID: 38f4614f3a82
Revises: 
Create Date: 2025-05-09 18:46:15.399811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38f4614f3a82'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('precio', sa.Integer(), nullable=True))
    op.add_column('productos', sa.Column('imagen_url', sa.String(), nullable=True))
    op.add_column('productos', sa.Column('autor', sa.String(), nullable=True))
    op.add_column('productos', sa.Column('whatsapp', sa.String(), nullable=True))
    op.alter_column('productos', 'descripcion',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('productos', 'telefono')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('productos', sa.Column('telefono', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('productos', 'descripcion',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('productos', 'whatsapp')
    op.drop_column('productos', 'autor')
    op.drop_column('productos', 'imagen_url')
    op.drop_column('productos', 'precio')
    # ### end Alembic commands ###
